### ISSUE TITLE
No input mask for issues in the sidebar

### ISSUE THREAD

**Issue by maddes8cht** [stateful/vscode-issue-explorer#15]
After installing the VSCode-iussue-explorer extension and restarting VSCode, I see an icon in the Activity bar, but the content in the Primary Side bar just says:

> The [GitHub Issue Explorer](https://marketplace.visualstudio.com/items?itemName=stateful.issue-explorer) allows you to quickly create GitHub issues while working on your code. Just select one or multiple lines, do a right click and pick Create Issue From Selection.
>
> Note: make sure you are working in a project that has git as version control system!
>
> [→ Open Walkthrough](command:issue-explorer.getStarted)

In the readme.md you write about "Install from inside VS Code" under 
> 5. enter your name, create todos and be happy.

I never got anything to enter my name or any credentials, and Github Issue Explorer is not mentioned in the "managed trusted extensions" list of Github account settings accesible in the lower left corner of VSCode.

I can select code and get the entry "Create Issue from selection" in the context menu, but it does nothing- no other window appears in the sidebar where I could enter the issue.

**Comment by christian-bromann** [comment]
Fixed in `v1.0.6` and just published to the Marketplace. Thank you for reporting.

**Comment by maddes8cht** [comment]
Tried it.
It "fixes" the phenomenon that the UI for creating an isue never showed up,  but the core problem seems still to be unresolved: it doesn't authorize t github, never asks for authorization, never shows up in the list of trusted extensions, and thus the submit button never is able to send anything to github and issues created in this extension never show up on github.

:(
So #8 and #15 also will be unresolved.
By the way, I would like to suggest that it is generally considered good practice to wait for feedback on changes made before closing an issue.

**Comment by maddes8cht** [comment]
Uninstalled extension, installed again.
Problem remains.
No authorisation in github is ever requested.

**Comment by christian-bromann** [comment]
@maddes8cht thanks for reporting back. Would you mind digging up any logs that are related to this? I wonder where the authorisation with GitHub fails since it was working on my `insiders` version.

**Comment by maddes8cht** [comment]
Hm

what kind of logs could it be?
The traces of this extension are particularly sparse. There are no extension settings.
I have no idea where the extension would log anything about trying to connect to Github.
If I open the Accounts menu (links below) and go to "Github - Manage Trusted Extensions", I see a list of extensions that all use github and have managed to connect.
Issue Explorer is not included in this list - that is, not only does it not have a checkmark in the checkbox, but it is actually not listed at all.
What other information would you like me to provide?

**Comment by christian-bromann** [comment]
Thanks for providing more information. I will look into this over the next days.
